# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a600b129544ce8be97839932e2638b3ff701e36061345abe9559fe0ee7659afe01f53de0392415f9dc0a2ed3c027f02ce9c32ad94bc7c0b7c1c6823ce189af

test:
  secret_key_base: 463d9416004ea567093a061e6c92d0783cd081d6250ba376cd1f11771c3de36a7e1e70b8e44150a134915e2c45efec04babe470e004591aacb3de4e98ed174d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
